### ISSUE TITLE
Replace text with actual button in qualityOfLife.md

### ISSUE THREAD

**Issue by MartinKjunior** [OSIPI/OSIPI_CAPLEX#59]
In `Copying reference to table data for publications` replace `COPY LINK` text with an actual button so people can test it out on that page.

**Comment by Aditish51** [comment]
@MartinKjunior Is someone working on this issue? Can I try it?

**Comment by MartinKjunior** [comment]
Completed as part of #65

**Comment by MRdep** [comment]
Hi Aditish,

I’ll try to add some more issues over the weekend, also add more detail to the ones already there because you might need more info.

One thing we are trying to do is to build a text converter which takes text written by researchers and adds the lexicon hyperlinks. Is this something you might be interested in doing for gsoc project?

Best wishes,

Ben





--------------------------------------------------------------------------
Ben Dickie, PhD
Senior Experimental Officer and Senior Research Fellow in Preclinical MRI
7T MRI laboratory, G727
Stopford Building
The University of Manchester
mob: 07837837807 | e: ***@***.***
------------------------------------------------------------------
________________________________

**Comment by Aditish51** [comment]
Hello Ben,

Thank you for reaching out and considering me for the project. Building a text converter to add lexicon hyperlinks to research texts sounds like an interesting and valuable project for enhancing accessibility and understanding in research documents. It will be helpful for the researchers to collaborate and communicate. 

I am definitely interested in exploring this project further and learning more about the requirements and goals. 

Also adding more detail to the existing issues and discussing potential enhancements over the weekend sounds like a great plan. I'm open to discussing the project in more depth and contributing to its development for the GSoC'24.

Looking forward to hearing more details and discussing further.

**Comment by Aditish51** [comment]
Hello Ben,

Thank you for reaching out and considering me for the project. Building a
text converter to add lexicon hyperlinks to research texts sounds like an
interesting and valuable project for enhancing accessibility and
understanding in research documents. It will be helpful for the researchers
to collaborate and communicate.

I am definitely interested in exploring this project further and learning
more about the requirements and goals.

Also adding more detail to the existing issues and discussing potential
enhancements over the weekend sounds like a great plan. I'm open to
discussing the project in more depth and contributing to its development
for the GSoC'24.

Looking forward to hearing more details and discussing further.
